// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBT2UEtzlnn5v_FdBw4_PZ45NDd17Rsak',
    appId: '1:207586543537:web:93bd8a8e2a86b680505f90',
    messagingSenderId: '207586543537',
    projectId: 'custos-d6d46',
    authDomain: 'custos-d6d46.firebaseapp.com',
    storageBucket: 'custos-d6d46.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBKe_93tJRB8ouCYaLaUtsdbeamKL5H0s',
    appId: '1:207586543537:android:af1e8fc0dc01e9f9505f90',
    messagingSenderId: '207586543537',
    projectId: 'custos-d6d46',
    storageBucket: 'custos-d6d46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIZKAe_JqEd0NKMtUXCCf7mFL_Zr3cYMU',
    appId: '1:207586543537:ios:4779a683c4b08f6b505f90',
    messagingSenderId: '207586543537',
    projectId: 'custos-d6d46',
    storageBucket: 'custos-d6d46.firebasestorage.app',
    iosBundleId: 'com.example.custos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIZKAe_JqEd0NKMtUXCCf7mFL_Zr3cYMU',
    appId: '1:207586543537:ios:4779a683c4b08f6b505f90',
    messagingSenderId: '207586543537',
    projectId: 'custos-d6d46',
    storageBucket: 'custos-d6d46.firebasestorage.app',
    iosBundleId: 'com.example.custos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBT2UEtzlnn5v_FdBw4_PZ45NDd17Rsak',
    appId: '1:207586543537:web:49e5ea1879240d53505f90',
    messagingSenderId: '207586543537',
    projectId: 'custos-d6d46',
    authDomain: 'custos-d6d46.firebaseapp.com',
    storageBucket: 'custos-d6d46.firebasestorage.app',
  );

}